import Vue from 'vue'

Vue.component('UiPopup', require('@/ui/Popup/Popup.vue').default)
Vue.component('UiField', require('@/ui/Field/Field.vue').default)
Vue.component('UiInput', require('@/ui/Input/Input.vue').default)
Vue.component('UiPanel', require('@/ui/Panel.vue').default)
Vue.component('UiContainer', require('@/ui/Container.vue').default)
Vue.component('UiIcon', require('@/ui/Icon.vue').default)
Vue.component('UiText', require('@/ui/Text/Text.vue').default)
Vue.component('UiTitle', require('@/ui/Title.vue').default)
Vue.component('UiPlaceholder', require('@/ui/Placeholder.vue').default)
Vue.component('UiIconLoader', require('@/ui/IconLoader.vue').default)
Vue.component('UiPopover', require('@/ui/Popover/Popover.vue').default)
Vue.component('UiButton', require('@/ui/Button/Button.vue').default)
Vue.component('UiCarousel', require('@/ui/Carousel/Carousel.vue').default)
Vue.component('UiCarouselItem', require('@/ui/Carousel/CarouselItem.vue').default)
Vue.component('UiFormValidator', require('@/ui/FormValidator.vue').default)
Vue.component('UiBack', require('@/ui/Back.vue').default)
Vue.component('UiLink', require('@/ui/Link.vue').default)
Vue.component('UiSwitch', require('@/ui/Switch/Switch.vue').default)
Vue.component('UiBadge', require('@/ui/Badge.vue').default)
Vue.component('UiPrice', require('@/ui/Price.vue').default)
Vue.component('UiAlert', require('@/ui/Alert/Alert.vue').default)

Vue.component('UiAvatar', require('@/ui/Avatar/Avatar.vue').default)
Vue.component('UiSelect', require('@/ui/Select/Select.vue').default)
Vue.component('UiDropdownMenu', require('@/ui/DropdownMenu/DropdownMenu.vue').default)
Vue.component('UiDropdownGroup', require('@/ui/DropdownMenu/DropdownGroup.vue').default)
