// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActiveTime: typeof import('./components/Schedule/components/ActiveTime.vue')['default']
    Appointment: typeof import('./components/Appointment/Appointment.vue')['default']
    AvailableArea: typeof import('./components/Schedule/components/AvailableArea.vue')['default']
    BalancePanel: typeof import('./components/BalancePanel/BalancePanel.vue')['default']
    Chart: typeof import('./components/Chart/Chart.vue')['default']
    Column: typeof import('./components/Schedule/components/Column.vue')['default']
    ColumnPlaceholder: typeof import('./components/Schedule/components/ColumnPlaceholder.vue')['default']
    DatePicker: typeof import('./components/DatePicker/DatePicker.vue')['default']
    FileUpload: typeof import('./components/FileUpload/FileUpload.vue')['default']
    FixedPanel: typeof import('./components/FixedPanel/FixedPanel.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    HourTile: typeof import('./components/Schedule/components/HourTile.vue')['default']
    InfoPanel: typeof import('./components/InfoPanel/InfoPanel.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    Navbar: typeof import('./components/Navbar/Navbar.vue')['default']
    'Navbar.desktop': typeof import('./components/Navbar/Navbar.desktop.vue')['default']
    'Navbar.mobile': typeof import('./components/Navbar/Navbar.mobile.vue')['default']
    NavbarItem: typeof import('./components/Navbar/components/NavbarItem.vue')['default']
    PopperMenu: typeof import('./components/PopperMenu/PopperMenu.vue')['default']
    PopperMenuInner: typeof import('./components/PopperMenu/PopperMenuInner.vue')['default']
    Popup: typeof import('./components/Popups/Popup.vue')['default']
    Popups: typeof import('./components/Popups/Popups.vue')['default']
    ProcedurePreview: typeof import('./components/ProcedurePreview/ProcedurePreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Schedule: typeof import('./components/Schedule/Schedule.vue')['default']
    SortableList: typeof import('./components/SortableList/SortableList.vue')['default']
    Specialist: typeof import('./components/Schedule/components/Specialist.vue')['default']
    Timeline: typeof import('./components/Schedule/components/Timeline.vue')['default']
    TimeOff: typeof import('./components/Schedule/components/TimeOff.vue')['default']
    TimetablePlaceholder: typeof import('./components/Schedule/components/TimetablePlaceholder.vue')['default']
    Toast: typeof import('./components/Toasts/Toast.vue')['default']
    Toasts: typeof import('./components/Toasts/Toasts.vue')['default']
  }
}
